Add Makefile for convenience
openSUSE/qem-dashboard pull request #1421
Opened 2024-07-22 09:53 UTC by okurz

New developers would have a hard time finding necessary dependencies and
commands to execute by needing to look into GHA definitions so instead
let's provide a convenient Makefile with help text.

2024-08-14 12:09 UTC, Martchus submitted a review, later dismissed

2024-08-14 12:12 UTC, Martchus commented
Although I must say that I find putting `sudo` and distribution-specific and package-manager-specific commands into the Makefile problematic. I would have at least prefixed the targets with e.g. `-debian` and `-cpanm`.

2024-08-14 12:23 UTC, okurz commented
> Although I must say that I find putting `sudo` and distribution-specific and package-manager-specific commands into the Makefile problematic. I would have at least prefixed the targets with e.g. `-debian` and `-cpanm`.

err, do you mean prefix or suffix? Should I rename `install-deps-perl` to `install-deps-cpanm` or `install-deps-perl-cpanm` or `cpanm-install-deps-perl`?

And what about sudo? Keep it, just add suffix/prefix debian?

2024-08-14 14:55 UTC, Martchus commented
Sorry, I mean suffix (although it doesn't really matter). And I suppose `sudo` just falls under `debian` :-)

2024-09-25 08:12 UTC, Martchus submitted a review, later dismissed

2024-09-25 09:30 UTC, okurz commented
Fixed missing name adaption in github action workflow. Sorry, you need to re-review as this project is configured to remove all approvals on pushed changes.

2024-10-21 12:56 UTC, baierjan requested changes

2024-10-21 13:08 UTC, okurz commented
@baierjan incorporated both of your suggestions

2024-10-21 13:39 UTC, baierjan commented on .github/workflows/linux.yml
> +          make install-deps-debian install-deps-cpanm
🤔 

```suggestion
          make install-deps-ubuntu install-deps-cpanm
```

2024-10-22 19:17 UTC, baierjan approved these changes

2024-10-25 09:21 UTC, merged